### ISSUE TITLE
Merge http and websocket ports (and idealy socketio)

### ISSUE THREAD

**Issue by benoitvidis** [kuzzleio/kuzzle-proxy#40]
As seen with @gandbox, we should use a single connection endpoint for http-alike protocols.

For Websocket, this implies to move the websocket plugin inside the proxy core and use the same http server.
SocketIo is very likely more problematic and will need more investigations on if/how this is possible at all.

**Comment by benoitvidis** [comment]
cf http://socket.io/docs/server-api/
The socket:Namespace option seems to be a good candidate to use.

**Comment by ballinette** [comment]
maybe nothing special is needed for `socket.io`, as it is initalized with "/socket.io" path by default... to be tested...
