### ISSUE TITLE
Proxy need a valid internet connexion to start

### ISSUE THREAD

**Issue by stafyniaksacha** [kuzzleio/kuzzle-proxy#42]
Steps to reproduce: 
* Connect to Internet
* Run the Kuzzle stack (it will download plugins for both kuzzle & proxy)
* Stop the stack & logout from internet
* Run the Kuzzle stack again 
  * proxy will not start
  * kuzzle will crash with a fatal error `Service "proxyBroker[proxyBroker]" failed to init within 10000ms` 

Tested commit: 94f40aa1f0cfddef62f03492a9823d1bc0d379c3

**Comment by scottinet** [comment]
Fixed with the plugin refactor
