### ISSUE TITLE
Add --abort_on_uncaught_exception to node's options in prod environment

### ISSUE THREAD

**Issue by scottinet** [kuzzleio/kuzzle-proxy#53]
When starting the proxy on a production environment, the following option should be added to node's interpreter: `--abort_on_uncaught_exception`

This creates a coredump if the process crashes because of an uncaught exception. Can be handy as a safety net if diagtools aren't notified about the crash and thus do not generate the coredump.

**Comment by ballinette** [comment]
as kuzzzle-proxy is deprecated => close
