### ISSUE TITLE
Add request headers to request context

### ISSUE THREAD

**Issue by ballinette** [kuzzleio/kuzzle-proxy#76]
in order to permit kuzzle to handle restrictions according to the context.

**Comment by ballinette** [comment]
blocked by https://github.com/kuzzleio/kuzzle-common-objects/pull/56

**Comment by scottinet** [comment]
As discussed, headers need to be put in `request.input` instead of `request.context`, as it makes perfect sense especially considering the `request.response.headers` counterpart.

I will write new issues to adapt Kuzzle to this new behavior.
