### ISSUE TITLE
Proxy sending requests to overloaded Kuzzle node

### ISSUE THREAD

**Issue by BaptisteKaliop** [kuzzleio/kuzzle-proxy#92]
Not sure if this issue is still valid on v1, but it is on : 586bb1677b1f01619806534004bad32a8d5641be

When a Kuzzle node in cluster mode is overloaded, Kuzzle keep sending requests to this node instead of avoiding this node due to the overload

**Comment by AnthonySendra** [comment]
Note: the cluster is configured in round-robin

**Comment by ballinette** [comment]
This will be soon deprecated in V1 and it's to much work to fix it in rc.x version
