### ISSUE TITLE
docker hub readme should contain documentation on how to use kuzzle in docker

### ISSUE THREAD

**Issue by justinmchase** [kuzzleio/kuzzle-proxy#95]
I went here:
https://hub.docker.com/r/kuzzleio/proxy/

But the documentation appears to only show how to use it from nodejs. I added this to my `docker-compose.yml` file but it doesn't seem to work:

```
test-proxy:
  image: kuzzleio/proxy
  ports:
    - "8888:7512"
```

Then from bash:
```
$ docker-compose up -d
$ curl -x "http://localhost:8888" "http://google.com"
{"message":"Client connection refused: no Kuzzle instance found","status":503}
```

What steps are missing?

**Comment by ballinette** [comment]
Hi @justinmchase 
Indeed, Kuzzle Proxy is not a generic HTTP proxy. It is a specific reverse proxy for [Kuzzle backend.](http://docs.kuzzle.io/guide/essentials/installing-kuzzle/).

So I guess this product is not the solution that you are looking for ;)

But I agree that the description is confusing. I will fix that.

**Comment by justinmchase** [comment]
I figured this out, I am using squid proxy and that fulfilled my usecase. Thanks.
